---
title: "summer_project"
format: html
editor: visual
---
```{r}
library(tidyverse)

```


```{r}
# This scipt takes raw QCEW data for each year and filters the data to a county level

qcew_processed_data <- function(YEAR) {
  file <- glue::glue("data/raw/download_qcew_{YEAR}_singlefile.zip")
  qcew_raw <- read_csv(file)
  qcew_county_total_YEAR <- qcew_raw |> 
# filtering for county
     filter(industry_code == "10", agglvl_code == 70, 
           size_code == 0, own_code == 0) |> 
# creates average employment for each quarter
    mutate(avg_emplvl = (month1_emplvl + month2_emplvl
                         + month3_emplvl) / 3) |> 
    select(area_fips, year, qtr, qtrly_estabs, total_qtrly_wages, 
           avg_wkly_wage, avg_emplvl)
# saving the processed data 
  name <- glue::glue("data/processed/qcew_county_total_{YEAR}.csv")
  write_csv(qcew_county_total_YEAR, name)
}
```

```{r}
dir.create("data/raw", recursive = TRUE, showWarnings = FALSE)

options(timeout = 1200)

qcew_data <- function(YEAR) {
  
  url <- glue::glue("https://data.bls.gov/cew/data/files/{YEAR}/csv/{YEAR}_qtrly_singlefile.zip")
  
  destination <- glue::glue("data/raw/download_qcew_{YEAR}_singlefile.zip")
  
  if (file.exists(destination)) {
    file.remove(destination)
  }
  
  download.file(url, destfile = destination, mode = "wb")
  
  message("Downloaded ", destination)
  
}
```

```{r}

# test qcew data processing

qcew_check <- function(YEAR){
  file <- glue::glue("data/processed/qcew_county_total_{YEAR}.csv")
  data <- read.csv(file)
  # counts number of rows
  nrow(data)
  data |> 
    group_by(qtr) |> 
    summarize(n_rows = n())
  data |> 
    # checking for one row per quarter for each county 
    group_by(qtr, area_fips) |> 
    count() |> 
    filter(n >1)
}
```